name: ltc
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.4.0
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - alsa-lib=1.2.3.2
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=10.0.1
  - asttokens=2.2.1
  - attrs=22.2.0
  - aws-c-auth=0.6.21
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.16
  - aws-c-http=0.6.29
  - aws-c-io=0.13.11
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.2.1
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.9.379
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.0
  - bleach=6.0.0
  - bokeh=2.4.3
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - cartopy=0.20.1
  - certifi=2022.12.7
  - cffi=1.14.6
  - cfitsio=4.0.0
  - cftime=1.6.2
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - comm=0.1.3
  - configobj=5.0.8
  - cryptography=39.0.0
  - curl=7.86.0
  - cycler=0.11.0
  - cython=0.29.33
  - cytoolz=0.12.0
  - dask=2023.3.1
  - dask-core=2023.3.1
  - dbus=1.13.6
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.3.1
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - flit-core=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.2
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2023.3.0
  - gdal=3.3.3
  - geos=3.10.0
  - geotiff=1.7.0
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - glog=0.6.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - icu=68.2
  - idna=3.4
  - importlib-metadata=6.1.0
  - importlib_metadata=6.1.0
  - importlib_resources=5.12.0
  - ipykernel=6.22.0
  - ipython=8.11.0
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_client=8.1.0
  - jupyter_contrib_core=0.4.0
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_nbextensions_configurator=0.6.1
  - jupyter_server=2.5.0
  - jupyter_server_fileid=0.8.0
  - jupyter_server_terminals=0.4.4
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.3
  - jupyterlab=3.6.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.20.0
  - kealib=1.4.15
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20220623.0
  - libarrow=10.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcrc32c=1.1.2
  - libcurl=7.86.0
  - libdap4=3.20.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=12.2.0
  - libgdal=3.3.3
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.68.4
  - libgomp=12.2.0
  - libgoogle-cloud=2.5.0
  - libgrpc=1.51.1
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=13.5
  - libprotobuf=3.21.12
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.0.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libutf8proc=2.8.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.3
  - markupsafe=2.1.2
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - msgpack-python=1.0.5
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbclassic=0.5.3
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.8.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - netcdf4=1.6.0
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89
  - numba=0.56.4
  - numpy=1.23.5
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - orc=1.8.2
  - packaging=23.0
  - pandas=1.5.3
  - pandoc=3.1.1
  - pandocfilters=1.5.0
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - partd=1.3.0
  - patsy=0.5.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=23.0.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.1.1
  - pooch=1.7.0
  - poppler=21.09.0
  - poppler-data=0.4.12
  - postgresql=13.5
  - proj=8.1.1
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=10.0.1
  - pycparser=2.21
  - pygments=2.14.0
  - pykdtree=1.3.7.post0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyproj=3.2.1
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyresample=1.26.1
  - pyrsistent=0.19.3
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.9.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-json-logger=2.0.7
  - python_abi=3.9
  - pytz=2022.7.1
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt=5.12.9
  - rasterio=1.2.10
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rioxarray=0.14.0
  - s2n=1.3.30
  - scipy=1.10.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.0
  - setuptools=67.6.0
  - shapely=1.8.0
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - tblib=1.7.0
  - terminado=0.17.1
  - tiledb=2.3.4
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzcode=2022g
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.40.0
  - xarray=2023.2.0
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - cadati==0.0.2
      - configparser==5.3.0
      - ipywidgets==8.0.5
      - ismn==1.3.3
      - jupyterlab-widgets==3.0.6
      - more-itertools==9.1.0
      - pygeobase==0.6.2
      - pygeogrids==0.4.2
      - pynetcf==0.4.0
      - pytesmo==0.14.4
      - repurpose==0.9
      - tqdm==4.65.0
      - widgetsnbextension==4.0.6
