name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - appdirs=1.4.4
  - arrow=1.2.2
  - astroid=2.6.6
  - asttokens=2.0.5
  - atomicwrites=1.4.0
  - autopep8=1.6.0
  - babel=2.9.1
  - backcall=0.2.0
  - binaryornot=0.4.4
  - black=19.10b0
  - blas=1.0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - conda=4.12.0
  - conda-package-handling=1.7.3
  - cookiecutter=1.7.3
  - cryptography=36.0.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - docutils=0.17.1
  - entrypoints=0.3
  - executing=0.8.3
  - expat=2.4.4
  - flake8=3.9.2
  - fontconfig=2.13.1
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - imagesize=1.3.0
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - inflection=0.5.1
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipykernel=6.9.1
  - ipython=8.2.0
  - ipython_genutils=0.2.0
  - isort=5.9.3
  - jbig=2.1
  - jedi=0.18.1
  - jeepney=0.7.1
  - jinja2=3.0.3
  - jinja2-time=0.2.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=6.1.12
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.1.2
  - keyring=23.4.0
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libarchive=3.5.2
  - libcurl=7.80.0
  - libdeflate=1.7
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libsolv=0.7.20
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - lzo=2.10
  - mamba=0.15.3
  - markupsafe=2.0.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mypy_extensions=0.4.3
  - nbclient=0.5.11
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - numpy-base=1.21.2
  - numpydoc=1.2
  - openssl=1.1.1n
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.7.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - poyo=0.5.0
  - prompt-toolkit=3.0.20
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.7.0
  - pycosat=0.6.3
  - pycparser=2.21
  - pydocstyle=6.1.1
  - pyflakes=2.3.1
  - pygments=2.11.2
  - pylint=2.9.6
  - pyls-spyder=0.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.2
  - python-lsp-black=1.0.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.2.4
  - python-slugify=5.0.2
  - python_abi=3.8
  - pyxdg=0.27
  - pyzmq=22.3.0
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt=5.9.7
  - qtawesome=1.0.3
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - readline=8.1.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.27.1
  - rope=0.22.0
  - rtree=0.9.7
  - ruamel_yaml=0.15.100
  - secretstorage=3.3.1
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - sphinx=4.4.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.1.5
  - spyder-kernels=2.1.3
  - sqlite=3.38.0
  - stack_data=0.2.0
  - testpath=0.5.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - three-merge=0.1.1
  - tinycss=0.4
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=5.1.1
  - typed-ast=1.4.3
  - typing_extensions=4.1.1
  - ujson=5.1.0
  - unidecode=1.2.0
  - urllib3=1.26.8
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wrapt=1.12.1
  - wurlitzer=3.0.2
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - affine==2.3.0
    - amqp==2.6.1
    - ascat==1.1.2
    - attrs==20.3.0
    - billiard==3.5.0.5
    - cadati==0.0.2
    - celery==4.1.1
    - cftime==1.4.1
    - click==7.1.2
    - click-plugins==1.1.1
    - cligj==0.7.1
    - colorcet==2.0.6
    - configobj==5.0.6
    - configparser==5.0.1
    - coverage==5.4
    - cycler==0.10.0
    - cython==0.29.21
    - dask==2021.2.0
    - django-countries==7.0
    - django-widget-tweaks==1.4.8
    - ease-grid==0.2
    - equi7grid==0.0.11
    - fiona==1.8.18
    - geopandas==0.8.2
    - geopathfinder==0.0.7
    - iniconfig==1.1.1
    - ismn==0.4
    - kombu==4.6.11
    - llvmlite==0.35.0
    - lxml==4.6.2
    - more-itertools==8.7.0
    - munch==2.5.0
    - netcdf4==1.5.6
    - numba==0.52.0
    - numpy==1.17.3
    - oldest-supported-numpy==0.15
    - packaging==20.9
    - pandas==1.2.2
    - param==1.10.1
    - parse==1.19.0
    - pluggy==0.13.1
    - psycopg2-binary==2.8.6
    - py==1.10.0
    - pyct==0.4.8
    - pygeobase==0.4.0
    - pygeogrids==0.3.2
    - pykdtree==1.3.4
    - pynetcf==0.2.2
    - pyproj==3.0.0.post1
    - pyresample==1.17.0
    - pyshp==2.1.3
    - pytesmo==0.13.3.post1.dev14+gcb25ddb
    - pytest==6.2.2
    - pytest-cov==2.11.1
    - pytest-django==4.1.0
    - pytest-mpl==0.12
    - pytileproj==0.0.13
    - pytz==2021.1
    - pyyaml==5.4.1
    - rasterio==1.2.6
    - redis==3.5.3
    - regex==2020.11.13
    - repurpose==0.8
    - scipy==1.6.0
    - seaborn==0.11.1
    - shapely==1.7.1
    - smos==0.2
    - snuggs==1.4.7
    - sqlparse==0.4.1
    - toolz==0.11.1
    - trollsift==0.3.5
    - veranda==0.1.1
    - vine==1.3.0
    - xarray==0.16.2
